version: '3'
services:
  
  transacao-api:
   build:
    context: ./
    dockerfile: ./Dockerfile
   image: ednelson/transacao
   ports:
    - 8080:8080
   links:
    - mysql-transacao
   depends_on:
    - mysql-transacao
   environment:
     DATABASE_URL: jdbc:mysql://mysql-transacao:3306/transacaodb
     KEYCLOAK_ISSUER_URI: http://keycloak/auth/realms/transacao
     KEYCLOAK_JWKS_URI: http://keycloak/auth/realms/transacao/protocol/openid-connect/certs
   restart: always
  
  mysql-transacao:
   image: mysql:8.0.25
   ports:
    - 3307:3306
   environment:
    - MYSQL_DATABASE=transacaodb
    - MYSQL_ROOT_PASSWORD=root

   volumes:
    - mysql-volume:/var/lib/mysql

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    image: jboss/keycloak
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
      - kafka
      - zookeeper
      - transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1
      #KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth

  transacoes:
    image: 'zupacademy/transacoes'
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  vault:
    image: vault:1.5.3
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_TOKEN: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_ADDR: http://127.0.0.1:8200

volumes:
  postgres-volume:
  mysql-volume: